### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by johandk89** [matthewmcgarvey/alfred-newrelic-workflow#1]
Hi

I added my new relic api key and account ID but I keep getting this error when typing `nr` into alfred

```
[2020-07-01 18:20:12][input.scriptfilter] Queuing argument ''
[2020-07-01 18:20:12][input.scriptfilter] Script with argument '(null)' finished
[2020-07-01 18:20:12][ERROR: input.scriptfilter] Code 1: 18:20:12 workflow.py:1579 DEBUG    data `id` stored as `cpickle`
18:20:12 workflow.py:1594 DEBUG    stored data loaded: /Users/johan/Library/Application Support/Alfred 3/Workflow Data/com.mmcgarvey.newrelic/id.cpickle
18:20:12 workflow.py:1579 DEBUG    data `key` stored as `cpickle`
18:20:12 workflow.py:1594 DEBUG    stored data loaded: /Users/johan/Library/Application Support/Alfred 3/Workflow Data/com.mmcgarvey.newrelic/key.cpickle
.
18:20:12 workflow.py:2057 DEBUG    ---------- New Relic ----------
18:20:12 nr.py:44 DEBUG    ARGS LENGTH: 
18:20:12 nr.py:45 DEBUG    1
18:20:12 nr.py:46 DEBUG    ^^^^^
18:20:12 workflow.py:1565 DEBUG    no data stored for `apps`
18:20:12 workflow.py:2074 ERROR    <urlopen error [Errno 61] Connection refused>
Traceback (most recent call last):
  File "/Users/johan/Dropbox/Sync/Alfred/Alfred.alfredpreferences/workflows/user.workflow.99A97787-6F45-4692-8D96-73B6B676A516/workflow/workflow.py", line 2067, in run
    func(self)
  File "nr.py", line 48, in main
    apps = get_apps(wf)
  File "nr.py", line 26, in get_apps
    r = web.get('https://api.newrelic.com/v2/applications.json', headers={'X-Api-Key': nrkey})
  File "/Users/johan/Dropbox/Sync/Alfred/Alfred.alfredpreferences/workflows/user.workflow.99A97787-6F45-4692-8D96-73B6B676A516/workflow/web.py", line 583, in get
    stream=stream)
  File "/Users/johan/Dropbox/Sync/Alfred/Alfred.alfredpreferences/workflows/user.workflow.99A97787-6F45-4692-8D96-73B6B676A516/workflow/web.py", line 571, in request
    return Response(req, stream)
  File "/Users/johan/Dropbox/Sync/Alfred/Alfred.alfredpreferences/workflows/user.workflow.99A97787-6F45-4692-8D96-73B6B676A516/workflow/web.py", line 214, in __init__
    self.raw = urllib2.urlopen(request)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 61] Connection refused>
18:20:12 workflow.py:2097 DEBUG    ---------- finished in 0.017s ----------
[2020-07-01 18:20:12][input.scriptfilter] {"items": [{"valid": false, "subtitle": "<urlopen error [Errno 61] Connection refused>", "icon": {"path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"}, "title": "Error in workflow 'New Relic'"}]}

**Comment by matthewmcgarvey** [comment]
Sorry, @johandk89. I don't use this workflow anymore and don't have access to the New Relic api to look into it.

I can only recommend that you add some debug lines to the workflow to make sure you have the correct api key. You might also try making that get request through curl to see if it is an issue outside of this workflow.

Here is the link to the api documentation for the endpoint this workflow uses: https://docs.newrelic.com/docs/apis/rest-api-v2/application-examples-v2/list-apps-host-ids-instance-ids#ids_all_apps
